name: InPACT
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python~=3.6
  - pandas==1.1.5
  - numpy==1.19.5
  - bedtools==2.30.0
  - pybedtools==0.9.0
  - htseq==0.9.1
  - scikit-learn==1.0.1
  - imbalanced-learn==0.8.1
  - joblib==1.1.0
  - pyfasta==0.5.2
  - subread==2.0.3
  - samtools==1.14
  - pip>=21
  - pip:
    - .
